### ISSUE TITLE
references to existing literature needed?

### ISSUE THREAD

**Issue by ps-account** [vsoch/scif#13]
Not sure if this was in the previous draft, or if deemed unnecessary.

**Comment by vsoch** [comment]
@rdwrt you are in charge of this issue! When the draft meets your satisfaction, ping me here and I'll add our final notes to the docs proper. Also, this should probably be moved to https://www.github.com/sci-f/sci-f.github.io (docs and spec are going to be based there so it's more a community thing separate from the client that implements it here!)

**Comment by vsoch** [comment]
@rdwrt I'm going to close this here, since the docs aren't hosted here. When you finish your review open another issue if you want to add background and existing literature to the website itself.
