### ISSUE TITLE
parts of the menu navigation buttons like this arrow are broken, lead to 404

### ISSUE THREAD

**Issue by ps-account** [vsoch/scif#14]
This arrow leads to a 404

![2018-01-11 17_38_40-the scientific filesystem](https://user-images.githubusercontent.com/84399/34835830-597d7ca8-f6f6-11e7-91c0-b51f124ace8a.png)

**Comment by vsoch** [comment]
hey @pimpim I just fixed this up - can you take a look and see if I missed any?

**Comment by ps-account** [comment]
Seems fixed!

**Comment by vsoch** [comment]
thanks @pimpim ! And good catch!
