### ISSUE TITLE
Suggestion: replace EV with ENV for environment variables

### ISSUE THREAD

**Issue by ps-account** [vsoch/scif#15]
I'd suggest to replace EV with ENV as it is a more commonly used terminology, e.g. in spec.md: 

https://github.com/vsoch/scif/blob/master/docs/spec/spec.md

**Comment by vsoch** [comment]
oh good catch! We might even be able to just remove that line - I don't reference the term further. What do you think?

**Comment by ps-account** [comment]
I'd keep it, anything that gives options to adapt or transfer ENV is great imho!

**Comment by vsoch** [comment]
Here you go @pimpim !! https://github.com/vsoch/scif/commit/f728998227d36d58e179fbcfd4a3f07a678650ef
