### ISSUE TITLE
Nextflow-SCIF example : Possible solution

### ISSUE THREAD

**Issue by saramonzon** [vsoch/scif#47]
Hi there,
First of all, thank you for all your documentation and work, I have learned a lot this past couple of weeks!

I found that you tried to make an example with nextflow-scif. I have been working on a Nextflow-SCIF-Singularity implementation and I think I got it working with some "buts" but working. 

If you want to take a look in case someone could use it is in this repo [BU-ISCIII/nextflow-scif](https://github.com/BU-ISCIII/nextflow-scif). Also, I have used some of your documentation for the README, I hope you don't mind. The goal is to create a template for easy development of new pipelines in our unit.

Please I would be very grateful if you could give me some feedback if you find the time! I am very new in containers and scif so surely there is something that could be improved!

Best regards
Sara

**Comment by vsoch** [comment]
hey Sara, this is great! Do you want to move the repo (and still maintain ownership) over to scif, and/or add a link to the docs? I can definitely help with the *buts* if needed. I would much enjoy helping to make it nextflow ready, as I'm a big fan :)

**Comment by saramonzon** [comment]
Of course, there is no problem, do you mean you are going to fork the repo, or you want me to move it? I don't think I have done it before, but I can see how to do is if this is the case. Also you can use/link the documentation as you wish, a lot of that is obtained from your docs anyway xD.
Yeah, I discovered all this container-nextflow universe just a couple of months ago and I am shaking up the whole bioinformatics unit infrastructure, it's awesome!

**Comment by vsoch** [comment]
Wicked!

I would suggest to either have it be a part of the nextflow set of repos, or I'd be happy to host it on scif! If the latter, I can also help to manage / update the code, and I would make you primary maintainer of it. Let me know what your preference is!

**Comment by saramonzon** [comment]
I think I prefer you to fork it and host it in scif first. Once you have it checked I can write to nextflow people and ask them if they want to add the repo to the list of nextflow repositories they have in nextflow-awesome. That way we have all bases covered XD.

**Comment by vsoch** [comment]
okay, definitely can do that! I'll fork and keep the sci-f master updated to yours. After I fork, is it all ready to "pretend I'm getting started using it" and I can submit a PR to your repo with feedback / suggestions?

**Comment by saramonzon** [comment]
That sounds great! I look forward to reading and including your suggestions and improvements! And yes, all should be just ready and working for anyone to use it, everytime I read it see something that could be improved, but that is the disease of this profession....

**Comment by vsoch** [comment]
haha, definitely! I'm going to fork and close the issue here. I'll open new issues on your board. I'm traveling now, but should still be able to work on this soon! :D
