### ISSUE TITLE
scif run working directory

### ISSUE THREAD

**Issue by bilke** [vsoch/scif#50]
I am running a container with:

```
singularity run example.simg some_file.prj
```

`some_file.prj` is a file in my current working directory on the host. The problem is that inside the container I guess the working directory is set to SCIF-app directory (e.g. `/scif/apps/ogs`) and consequently my app executable cannot find this file.

When running the container with the following it works:

```
singularity run example.simg $PWD/some_file.prj
```

Is the working directory always changed to the SCIF-app directory?
More info on my setup below.
----

The runscript of the container is: `exec scif run ogs "$@"`.

`ogs` is a SCIF-app:

```
%appinstall ogs
    ...
%apprun ogs
    exec ogs
```

Full recipe files:

- [Singularity.def](https://jenkins.opengeosys.org/job/ufz/job/ogs-container-maker/job/master/41/artifact/_out/singularity/openmpi-off/conan/Singularity.def/*view*/), the SCIF-related part is at the end of the file
- [ogs.scif](https://jenkins.opengeosys.org/job/ufz/job/ogs-container-maker/job/master/41/artifact/_out/singularity/openmpi-off/conan/ogs.scif/*view*/)

**Comment by vsoch** [comment]
Yes this is expected behavior. When you run an app it is run in context of that app, meaning it’s directory.

**Comment by bilke** [comment]
Ok thanks!
