### ISSUE TITLE
singularity run --app support?

### ISSUE THREAD

**Issue by bilke** [vsoch/scif#51]
I built a container with some scif apps which where installed via `scif install ...`. I can run them with `scif`:

```bash
singularity exec container.simg scif run app_foo
```

I would expect that I can also run them with the `singularity run --app` syntax:

```
singularity run --app app_foo container.simg
```

But in this case there is no runscript defined:

```
No Singularity runscript for contained app: app_foo
```

Also `singularity test --app` does not work too but `singularity help --app` works!

Bug or intended? Thanks!

**Comment by vsoch** [comment]
The syntax:

```bash
singularity run --app app_foo container.simg
```
is using singularity as the controller for apps, so if there is a bug in the implementation you should take it up on the sylabs board --> https://github.com/sylabs/singularity/issues Feel free to leave this open if/when you have any more questions!

**Comment by bilke** [comment]
@vsoch Ok I think I found the reason:

The `runscript` for the app installed via `scif install ..` is existing but is not marked as executable:

```
ls -ll /scif/apps/app_foo/scif

-rw-r--r--. 1 root root 357 Oct 30 12:30 app_foo.scif
-rw-r--r--. 1 root root  27 Oct 30 12:30 runscript
-rw-r--r--. 1 root root  50 Oct 30 12:30 runscript.help
-rw-r--r--. 1 root root  30 Oct 30 12:30 test.sh
```

But singularity tests the file for it:

https://github.com/sylabs/singularity/blob/master/etc/actions/run#L11-L12

I guess `runscript` and `test.sh` should be `chmod +x`. Maybe here: https://github.com/vsoch/scif/blob/ee6dd5533a7fffe423fcd995552b05f1253982c3/scif/utils/fileio.py#L80-L86

or here: https://github.com/vsoch/scif/blob/ee6dd5533a7fffe423fcd995552b05f1253982c3/scif/main/install.py#L223

**Comment by vsoch** [comment]
Definitely a bug! GIve me a few minutes I'll get a fix for you done.

**Comment by vsoch** [comment]
okay here is how to test, let me know if this fixes the issue:

```bash
pip uninstall scif
# do the above until it tells you not installed to remove any previous versions
git clone -b fix/script-chmod https://www.github.com/vsoch/scif
cd scif
python setup.py install
```

**Comment by bilke** [comment]
Thanks a lot it works!

**Comment by vsoch** [comment]
Great! Thanks for testing, closing issue.

https://pypi.org/project/scif/0.0.76/
