### ISSUE TITLE
Add better background / introduction page

### ISSUE THREAD

**Issue by vsoch** [vsoch/scif#7]
The user not familiar with the reproducibility crisis or container technology will want something more substantial to read

**Comment by ps-account** [comment]
I remember we had a few discussions and references on this in a previous draft. Maybe we can dig that up? Also I'll go and check for updated info.

**Comment by vsoch** [comment]
oh I have (and finished) all this - it's just not "re-added" in this version from the manuscript. It's on my todo :)

**Comment by vsoch** [comment]
The docs are now maintained at sci-f.github.io!
