### ISSUE TITLE
Add other integration examples

### ISSUE THREAD

**Issue by vsoch** [vsoch/scif#9]
Help wanted! Let's get some other bases for examples. Eg., Other container technologies, but why not a GitHub repo example? The docs should be better organized to have a page that shows equivalent commands across bases, but then detailed separate walkthroughs for each.

**Comment by ps-account** [comment]
E.g. An R or Python package to be cloned from github?

**Comment by vsoch** [comment]
hey @rdwrt I can take a shot at this! Any suggestions?

**Comment by ps-account** [comment]
Maybe someone made a Keras or Tensorflow application or custom wrapper, shall I try to find examples?

**Comment by vsoch** [comment]
Sure!

**Comment by ps-account** [comment]
How about the foolbox: https://github.com/bethgelab/foolbox

But it's a library more then a set of apps. Still relevant for a common scientifc tool

**Comment by vsoch** [comment]
What would another example add? We already have the hello world, metrics, hpc, snakemake, and carrierseq pipelines.

**Comment by ps-account** [comment]
I don't know, you opened this ticket? :)

**Comment by vsoch** [comment]
Haha good point :) I definitely satisfied this issue, we have several updated and new examples! Apologies for my own /bonk
